# Generated by Django 3.0.6 on 2021-08-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_no', models.IntegerField()),
                ('owner_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('mbl_no', models.BigIntegerField()),
                ('aadhar_no', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
