# Generated by Django 3.0.6 on 2021-08-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('saddress', models.CharField(max_length=50)),
                ('smailid', models.CharField(max_length=20)),
                ('sphoneno', models.BigIntegerField()),
                ('sdob', models.IntegerField()),
                ('sdistrict', models.CharField(max_length=20)),
                ('sage', models.IntegerField()),
                ('saadhar', models.IntegerField()),
            ],
        ),
    ]
