# Generated by Django 3.0.6 on 2021-08-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='sdob',
        ),
        migrations.AlterField(
            model_name='seller',
            name='smailid',
            field=models.CharField(max_length=50),
        ),
    ]
