# Generated by Django 3.2.6 on 2021-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bno', models.CharField(max_length=50)),
                ('Oname', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=50)),
                ('Adress', models.CharField(max_length=50)),
                ('Adahar', models.CharField(max_length=50)),
                ('Emailid', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
