# Generated by Django 3.0.6 on 2021-08-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=50)),
                ('sellername', models.CharField(max_length=20)),
                ('manuname', models.CharField(max_length=50)),
                ('manudate', models.IntegerField()),
                ('expdate', models.IntegerField()),
            ],
        ),
    ]
