# Generated by Django 3.0.6 on 2021-08-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('mblno', models.BigIntegerField()),
                ('lastdonateddate', models.DateField()),
            ],
        ),
    ]
