# Generated by Django 3.0.6 on 2021-08-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_code', models.IntegerField()),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_description', models.CharField(max_length=50)),
                ('pro_price', models.IntegerField()),
            ],
        ),
    ]
